//
// GetRecipes200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetRecipes200Response: Codable, JSONEncodable, Hashable {

    public var recipes: [RecipesInner]?

    public init(recipes: [RecipesInner]? = nil) {
        self.recipes = recipes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case recipes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(recipes, forKey: .recipes)
    }
}

